p=project_root_path/'apps/vis-tui/src/com/blockether/vis/tui/dialogs.clj'; print(patch(p,[{'from':'1854:afa','replace':'      (fn [{:keys [selected query] :as state} key {:keys [total filtered list-h]}]'}, {'from':'1860:b15','to':'1861:092','replace':'              KeyType/ArrowUp (assoc state :selected (clampf (dec (long selected))))
              KeyType/ArrowDown (assoc state :selected (clampf (inc (long selected))))
              KeyType/PageUp (assoc state :selected (clampf (- (long selected) (long list-h))))
              KeyType/PageDown (assoc state :selected (clampf (+ (long selected) (long list-h))))'}, {'from':'1987:df8','to':'1990:3e5','replace':'               KeyType/ArrowUp (do (swap! selected #(p/clamp (dec (long %)) 0 (max 0 (dec total))))
                                   (recur))
               KeyType/ArrowDown (do (swap! selected #(p/clamp (inc (long %)) 0 (max 0 (dec total))))
                                     (recur))
               KeyType/PageUp (do (swap! selected #(p/clamp (- (long %) (long content-h))
                                                            0
                                                            (max 0 (dec total))))
                                  (recur))
               KeyType/PageDown (do (swap! selected #(p/clamp (+ (long %) (long content-h))
                                                              0
                                                              (max 0 (dec total))))
                                    (recur))'}, {'from':'4635:c35','to':'4638:3e5','replace':'                         KeyType/ArrowUp (do (swap! selected #(move-settings-selection rows % -1))
                                             (recur))
                         KeyType/ArrowDown (do (swap! selected #(move-settings-selection rows % 1))
                                               (recur))
                         KeyType/PageUp (do (swap! selected #(move-settings-selection rows % (- visible-h)))
                                            (recur))
                         KeyType/PageDown (do (swap! selected #(move-settings-selection rows % visible-h))
                                              (recur))'}, {'from':'4997:df8','to':'5000:de3','replace':'                 KeyType/ArrowUp (do (swap! selected #(p/clamp (dec (long %)) 0 (max 0 (dec total))))
                                     (recur))
                 KeyType/ArrowDown
                 (do (swap! selected #(p/clamp (inc (long %)) 0 (max 0 (dec total)))) (recur))
                 KeyType/PageUp (do (swap! selected #(p/clamp (- (long %) body-h) 0 (max 0 (dec total))))
                                    (recur))
                 KeyType/PageDown (do (swap! selected #(p/clamp (+ (long %) body-h) 0 (max 0 (dec total))))
                                      (recur))'}, {'from':'6079:bb5','to':'6084:ea6','replace':'                     KeyType/ArrowDown
                     (if (and (input/reorder-modifier? key) (pos? total))
                       (if-let [id (:id (:target (nth visible-rows @selected)))]
                         {:action :reorder :id id :dir :down}
                         (recur))
                       (do (swap! selected #(p/clamp (inc (long %)) 0 (max 0 (dec total)))) (recur)))
                     KeyType/PageUp (do (swap! selected #(p/clamp (- (long %) page-rows)
                                                                  0
                                                                  (max 0 (dec total))))
                                        (recur))
                     KeyType/PageDown (do (swap! selected #(p/clamp (+ (long %) page-rows)
                                                                    0
                                                                    (max 0 (dec total))))
                                          (recur))'}, {'from':'6486:af9','to':'6487:2c0','replace':'               KeyType/ArrowUp (do (swap! scroll #(max 0 (dec (long %)))) (recur))
               KeyType/ArrowDown (do (swap! scroll #(min max-scroll (inc (long %)))) (recur))
               KeyType/PageUp (do (swap! scroll #(max 0 (- (long %) (long content-h)))) (recur))
               KeyType/PageDown (do (swap! scroll #(min max-scroll (+ (long %) (long content-h))))
                                    (recur))'}, {'from':'6638:af9','to':'6639:2c0','replace':'                 KeyType/ArrowUp (do (swap! scroll #(max 0 (dec (long %)))) (recur))
                 KeyType/ArrowDown (do (swap! scroll #(min max-scroll (inc (long %)))) (recur))
                 KeyType/PageUp (do (swap! scroll #(max 0 (- (long %) (long content-h)))) (recur))
                 KeyType/PageDown (do (swap! scroll #(min max-scroll (+ (long %) (long content-h))))
                                      (recur))'}]))